### ISSUE TITLE
How to use FirefoxDriver?

### ISSUE THREAD

**Issue by artkpv** [ObjectivityLtd/Test.Automation#71]
Hello, thanks for the tool.

Breaks with:
```
One or more errors occurred.
  Exception doesn't have a stacktrace

System.InvalidOperationException
Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line (SessionNotCreated)
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at Objectivity.Test.Automation.Common.DriverContext.Start()
```

app.config:
```
    <add key="browser" value="Firefox" />
```

packages.config
```
  <package id="Objectivity.Test.Automation.Common.xUnit" version="3.1.3" targetFramework="net462" />
  <package id="Selenium.Support" version="3.11.2" targetFramework="net462" />
  <package id="Selenium.WebDriver" version="3.11.2" targetFramework="net462" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.38.0" targetFramework="net462" />
  <package id="Selenium.WebDriver.GeckoDriver" version="0.20.1" targetFramework="net462" />
  <package id="Selenium.WebDriver.IEDriver" version="3.11.1" targetFramework="net462" />

```

In PATH: `"C:\Program Files\Mozilla Firefox\".

FF 59.0.2 (64-bit)

**Comment by artkpv** [comment]
Does not work with:
```
   <add key="UseDefaultFirefoxProfile" value="true"/>
```

Starts with `  <add key="browser" value="FirefoxPortable" />     <add key="FireFoxPath" value="C:\Program Files\Mozilla Firefox\firefox.exe" />`. But works slow.

**Comment by raczeja** [comment]
it's 32 bit version of geckodriver, if you are using FireFox 64 bit you have to uninstall current version and install https://www.nuget.org/packages/Selenium.WebDriver.GeckoDriver.Win64/ in your solution.
